from tkinter import *
window = Tk()
window.title("Login page")
window.geometry("400x200")
lbl = Label(window, text="User name", font=("Helvectica", 16))
lbl.place(x=60, y=50)
txtfld = Entry(window, text="This is widget", bd=5)
txtfld.place(x=200, y=50)
lbl2 = Label(window, text="Password", font=("Helvectica", 16))
lbl2.place(x=60, y=80)
txtfld1 = Entry(window, text="This is widget", bd=5)
txtfld1.place(x=200, y=80)
btn = Button(window, text="SignIn", fg="blue")
btn.place(x=100, y=150)
btn = Button(window, text="SignUp", fg="blue")
btn.place(x=200, y=150)
window.mainloop()